server:
  port: 80

spring:
  config:
    activate:
      on-profile: local

  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  redis:
    host: redis
    port: 6379

  datasource:
    username: root
    password: dlqhfka
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://host.docker.internal:3307/pageflow?useSSL=false&autoReconnect=true
    url: jdbc:mysql://db:3306/pageflow?autoReconnect=true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:

          naver:
            scope: profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/naver'

          google:
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/google'

          github:
            scope: user:email, read:user
            client-name: github
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/github'


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


custom:
  site:
    base-url: 'http://localhost:${server.port}'
    login-form-uri: '/login'
    refresh-token-expire-days: 30
  email:
    email-verify-sender: verify@pageflow.org
    no-reply-sender: no-reply@pageflow.org
  defaults:
    default-user-profile-img: /img/default-profile-image.png
    default-book-cover-img: /img/default-book-cover-img.png
  admin:
    username: admin
    password: admin
    email: pagefloworg@gmail.com
  files:
    img:
      base-url: /files/img
#      directory: C:/Users/SBS/local/uploads/img
#      directory: C:/Users/gsw05/local/uploads/img
      directory: /Users/sechan/local/uploads/img