spring:
  profiles:
    active: dev
    include:
      - secret

  output:
    ansi:
      enabled: always

#server:
#  servlet:
#    session:
#      persistent: false


logging:
  level:
    org:
#    root: DEBUG
#      pageflow:
#        domain:
#          book:
#            service: DEBUG
#      springframework:
#        security: DEBUG
#        jdbc:
#          core: DEBUG
